version: '3'
services:
   app:
    container_name: docker-node-mongo1
    restart : always 
    build: .
    ports : 
     - '8072:7082'
    links :
     - mongo  
   mongo:
    container_name: mongo
    image : mongo
    ports : 
     - '27017:27017'
    
         
