version: '3'
services:
   app:
    container_name: docker-node-redis
    restart : always 
    build: .
    ports : 
     - '8072:7082'
    links :
     - redis  
   redis:
    container_name: redis
    image : redis
    ports : 
     - '6379:6379'
    
         
